SELECT i.ITEM_ID, i.ITEM_NAME
FROM ITEM_INFO i
JOIN ITEM_TREE t
    ON i.ITEM_ID = t.ITEM_ID
WHERE t.PARENT_ITEM_ID IS NULL
ORDER BY i.ITEM_ID

# ITEM_INFO 테이블을 기준으로, ITEM_TREE와 JOIN (ITEM_ID를 기준)
# IS NULL을 사용하여 ROOT 아이템 찾기
# ITEM_ID 기준 오름차순 정렬