SELECT YEAR(s.SALES_DATE) AS YEAR, MONTH(s.SALES_DATE) AS MONTH, COUNT(DISTINCT s.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT s.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1)
FROM ONLINE_SALE s
JOIN USER_INFO u 
    ON s.USER_ID = u.USER_ID
WHERE YEAR(u.JOINED) = 2021
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;