WITH RankTable AS (
    SELECT MEMBER_ID, COUNT(*) AS review_count
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
)
SELECT m.MEMBER_NAME, r.REVIEW_TEXT, 
    DATE_FORMAT(r.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE m
JOIN REST_REVIEW r 
    ON m.MEMBER_ID = r.MEMBER_ID
JOIN (
    SELECT DISTINCT MEMBER_ID
    FROM RankTable
    WHERE review_count = (SELECT MAX(review_count) FROM RankTable)
) max_members
    ON r.MEMBER_ID = max_members.MEMBER_ID
ORDER BY r.REVIEW_DATE ASC, r.REVIEW_TEXT ASC;
