SELECT ID, FISH_NAME, LENGTH
FROM (
  SELECT
    FI.ID, FN.FISH_NAME, FI.LENGTH,
    RANK() OVER (PARTITION BY FI.FISH_TYPE ORDER BY FI.LENGTH DESC) AS rnk
  FROM FISH_INFO FI
  JOIN FISH_NAME_INFO FN
    ON FI.FISH_TYPE = FN.FISH_TYPE
) T
WHERE rnk = 1
ORDER BY ID;