WITH SKILL_CODES AS (
    SELECT BIT_OR(CODE) AS SKILL_CODE 
    FROM SKILLCODES 
    GROUP BY CATEGORY 
    HAVING CATEGORY = 'Front End'
), SKILL_GRADE AS (
    SELECT
        CASE
            WHEN d.SKILL_CODE & s.SKILL_CODE 
                AND d.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python')
                THEN 'A'
            WHEN d.SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') 
                THEN 'B'
            WHEN d.SKILL_CODE & s.SKILL_CODE 
                THEN 'C'
            ELSE NULL
        END AS GRADE, d.ID, d.EMAIL
    FROM DEVELOPERS d, SKILL_CODES s
)
SELECT GRADE, ID, EMAIL
FROM SKILL_GRADE
WHERE GRADE IS NOT NULL
ORDER BY GRADE, ID;
